apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: inject-proxy-values
    app.kubernetes.io/part-of: common-admission-policies

commonAnnotations:
  kubernetes.io/description: This policy injects `HTTP_PROXY` env vars into all containers
    launched.

resources:
- policy.yaml
- policy-binding.yaml
- params.yaml
