commonLabels:
  app.kubernetes.io/name: block-nodeport-service
  app.kubernetes.io/part-of: common-validating-policies

commonAnnotations:
  kubernetes.io/description: This policy prevents the use of NodePort type services to avoid bypassing NetworkPolicy enforcement.

resources:
  - policy.yaml
  - policy-binding.yaml
