apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: block-latest-tag
    app.kubernetes.io/part-of: common-admission-policies

commonAnnotations:
  kubernetes.io/description: This policy prevents the use of any container image using the "latest" tag.

resources:
  - policy.yaml
  - policy-binding.yaml
